### ISSUE TITLE
`set-output` command is deprecated 

### ISSUE THREAD

**Issue by LuckyTurtleDev** [baptiste0928/cargo-install#10]
Using this action I did get the following warning:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by baptiste0928** [comment]
Hello ! This will be fixed in the next release (see #6).
