### ISSUE TITLE
Don't hash the crate name in the cache key

### ISSUE THREAD

**Issue by ForsakenHarmony** [baptiste0928/cargo-install#11]
I'd like to see the cached crate when looking at the caches for the repo, right now for example I see like 10 entries with `cargo-install-{hash}`

**Comment by baptiste0928** [comment]
Hello! Thanks for the suggestion, I just released a new update that changes the cache key format. Since it is a major update, you'll need to manually update your workflows to use the `v2` tag ([changelog](https://github.com/baptiste0928/cargo-install/releases/tag/v2.0.0)).
