### ISSUE TITLE
Update to node20 following node16 deprecation

### ISSUE THREAD

**Issue by HadrienG2** [baptiste0928/cargo-install#21]
I recently saw this warning pop up in my CI logs:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: baptiste0928/cargo-install@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by baptiste0928** [comment]
I published [v3.0.0](https://github.com/baptiste0928/cargo-install/releases/tag/v3.0.0) which uses Node 20. You will need to update your workflows as this is a a major version:

```diff
-uses: baptiste0928/cargo-install@v2
+uses: baptiste0928/cargo-install@v3
```
