### ISSUE TITLE
Planned features for cargo-install v2

### ISSUE THREAD

**Issue by baptiste0928** [baptiste0928/cargo-install#5]
I plan to work on a new major release (with breaking changes) soon.

- [ ] Use exact crate version if full version specified. See #7.
- [ ] Support installing multiple crates at once. See #4.
- [ ] Set `locked` to `true` by default to prevent sudden CI failures.
- [x] Update to Node.js v16.

**Comment by ForsakenHarmony** [comment]
> Use exact crate version if full version specified (e.g `0.5.2` => `=0.5.2`, `0.5` => `^0.5`).

Please don't do this based on the length of the version number

**Comment by baptiste0928** [comment]
In what situations do you think this would be a bad idea? The current behavior (always default to `^`) can cause CI breakages even if a fixed version is not specified. This behavior can be overwritten by specifying an explicit semver range.

**Comment by baptiste0928** [comment]
v2 has been released: https://github.com/baptiste0928/cargo-install/releases/tag/v2.0.0
