### ISSUE TITLE
Update lockfile to fix set-output warning

### ISSUE THREAD

**Issue by sunshowers** [baptiste0928/cargo-install#6]
Hi there!

When installing a package using this action, I've been getting these warnings:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Based on a quick look a simple lockfile update should fix this. Could you do so and publish an update? Thanks!

**Comment by baptiste0928** [comment]
Fixed in fa40bf603135b3c9f87c70bb423f77a1257dde12, it will be published with the next release.
