### ISSUE TITLE
Latest version being installed even though a fixed version is specified

### ISSUE THREAD

**Issue by sunshowers** [baptiste0928/cargo-install#7]
Hi again --

Noticed that the latest version of a crate is being installed even though a fixed version is specified.

For example, this workflow installed version 0.22.2: https://github.com/nextest-rs/nextest/actions/runs/3389729301/jobs/5633134431

With this workflow file: https://github.com/nextest-rs/nextest/actions/runs/3389729301/workflow#L104-L107

Could you look into this? Thanks!

**Comment by sunshowers** [comment]
Oh I think I need to specify the version with an equals sign. Wondering if this is caused by a difference between cargo's and node's respective meanings of semver version requirements.

**Comment by baptiste0928** [comment]
Thanks for reporting this bug!

Node treats caret requirements [the same way as cargo](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004), but this isn't properly implemented in the [`compare-versions`](https://github.com/omichelsen/compare-versions) package that is used to handle version requirements (https://github.com/omichelsen/compare-versions/issues/65).

I will switch to the [`semver`](https://www.npmjs.com/package/server) package (that is internally used by npm).

**Comment by sunshowers** [comment]
Thanks! What do you think of the suggestion to use the exact version if one is specified that way?

**Comment by baptiste0928** [comment]
Hi again ! I switched to `semver` in the [`next`](https://github.com/baptiste0928/cargo-install/tree/next) branch. Can you please test it on your workflow and tell me if it works?

You can use the `next` branch in your workflow with the following syntax:
```yaml
-  uses: baptiste0928/cargo-install@next
```

> What do you think of the suggestion to use the exact version if one is specified that way?

It's a good idea, I added this to the planned features for v2 (#5).

**Comment by begleynk** [comment]
Just swinging by to report that this didn't seem to work for me in the `next` branch with the caret syntax:
```
Run baptiste0928/cargo-install@next      # Using next branch
  with:
    crate: tauri-cli
    version: ^1.0.0-rc.10      # Explicit version
    locked: false
  env:
     ...
Installing tauri-cli ...
  Fetching crate information on crates.io ...
  Installation settings:
     version: 1.2.2         # Version gets ignored
...
```

**Comment by MeerKatDev** [comment]
This still picks up the last one (v0.23.0)
```  
    - name: Install uniffi_bindgen
      uses: baptiste0928/cargo-install@v1
         with:
           crate: uniffi_bindgen
           version: "0.22.0"
```

**Comment by baptiste0928** [comment]
I just released an update that switches to `semver` for version resolution, this should fix this issue :smile:
