### ISSUE TITLE
Warnings about using Node12

### ISSUE THREAD

**Issue by richb-hanover** [baptiste0928/cargo-install#8]
In my project, I'm seeing deprecation warnings about Node12. They look like:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: baptiste0928/cargo-install@v1

I see that your `action.yml` file does specify Node16 - Can you give any hints about how to avoid the warning above? Many thanks.

**Comment by baptiste0928** [comment]
Hello! The action was updated to Node.js 16 in a commit that hasn't yet been released. I will publish an update soon.

**Comment by richb-hanover** [comment]
Excellent. Thank you!

**Comment by baptiste0928** [comment]
I have rolled back the changes for the 1.3.1 release to avoid any breakage. The removal of node 12 for actions is planned for this summer, I will release a new major version before then.

**Comment by max-sixty** [comment]
OK, thanks @baptiste0928 .

BTW your action has been great — we've now replaced all similar ones in PRQL with it, and I've been recommending it to others. Thanks for your work!

**Comment by baptiste0928** [comment]
Thank you, I appreciate your message! Glad to hear that my work has been helpful to you and your team.

**Comment by baptiste0928** [comment]
I finally fixed this warning in the latest version! Since it's a major update, you'll need to manually update your workflows to use the `v2` tag ([changelog](https://github.com/baptiste0928/cargo-install/releases/tag/v2.0.0)).
